name: nexus
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - caddy_master-network
volumes:
  nexus-data: {}

networks:
  caddy_master-network:
    external: true
