name: illchess
services:
  # Game service
  game-db:
    container_name: game-db
    image: redis:7.0.11-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  chess-game-service:
    container_name: illchess-game-service
    image: shane3102/illchess-game-service
    ports:
      - 8080:8080
    depends_on:
      game-db:
        condition: service_healthy
    environment:
      - REDIS_HOSTNAME=6379
      - REDIS_HOSTNAME=game-db
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  # Stockfish service
  chess-stockfish-service:
    container_name: illchess-stockfish-service
    image: shane3102/illchess-stockfish-service
    ports:
      - 2137:2137
    environment:
      - URLS_GAME-SERVICE=http://illchess-game-service:8080

  # Player info service
  player-info-db:
    container_name: player-info-db
    image: mysql
    environment:
      MYSQL_DATABASE: player_info_db
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    expose:
      - '3306'
  chess-player-info-service:
    container_name: illchess-player-info-service
    image: shane3102/illchess-player-info-service
    ports:
      - 1025:420
    depends_on:
      player-info-db:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://player-info-db:3306/player_info_db
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
      - RABBITMQ-HOST=rabbit-mq
      - RABBITMQ-PORT=5672
      - RABBITMQ-USERNAME=guest
      - RABBITMQ-PASSWORD=guest

  # Api gateway
  chess-api-gateway:
    container_name: illchess-gateway
    image: shane3102/illchess-gateway
    ports:
      - 1337:1337
    environment:
      SPRING_CLOUD_GATEWAY_DEFAULT-FILTERS[0]: StripPrefix=2
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://illchess-game-service:8080
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/gateway/game/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://illchess-stockfish-service:2137
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path=/gateway/stockfish/**
      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://illchess-player-info-service:420
      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: Path=/gateway/player-info/**

  # Frontend
  chess-frontend:
    container_name: illchess-frontend
    image: shane3102/illchess-frontend
    ports:
      - 4200:80
    depends_on:
      chess-api-gateway:
        condition: service_started
      chess-game-service:
        condition: service_started

  # Shared
  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
